import { CountryNameAndCode } from "./DataTypes";

export const CountryAndCode: CountryNameAndCode[] = [
  { label: "Afghanistan", value: "af" },
  { label: "Albania", value: "al" },
  { label: "Algeria", value: "dz" },
  { label: "Argentina", value: "ar" },
  { label: "Australia", value: "au" },
  { label: "Austria", value: "at" },
  { label: "Bangladesh", value: "bd" },
  { label: "Belgium", value: "be" },
  { label: "Brazil", value: "br" },
  { label: "Canada", value: "ca" },
  { label: "Chile", value: "cl" },
  { label: "China", value: "cn" },
  { label: "Colombia", value: "co" },
  { label: "Czech Republic", value: "cz" },
  { label: "Denmark", value: "dk" },
  { label: "Egypt", value: "eg" },
  { label: "Finland", value: "fi" },
  { label: "France", value: "fr" },
  { label: "Germany", value: "de" },
  { label: "Greece", value: "gr" },
  { label: "Hungary", value: "hu" },
  { label: "India", value: "in" },
  { label: "Indonesia", value: "id" },
  { label: "Ireland", value: "ie" },
  { label: "Italy", value: "it" },
  { label: "Japan", value: "jp" },
  { label: "Kenya", value: "ke" },
  { label: "Malaysia", value: "my" },
  { label: "Mexico", value: "mx" },
  { label: "Netherlands", value: "nl" },
  { label: "New Zealand", value: "nz" },
  { label: "Nigeria", value: "ng" },
  { label: "Norway", value: "no" },
  { label: "Pakistan", value: "pk" },
  { label: "Philippine", value: "ph" },
  { label: "Poland", value: "pl" },
  { label: "Portugal", value: "pt" },
  { label: "Russia", value: "ru" },
  { label: "Saudi Arabia", value: "sa" },
  { label: "South Africa", value: "za" },
  { label: "South Korea", value: "kr" },
  { label: "Spain", value: "es" },
  { label: "Sweden", value: "se" },
  { label: "Switzerland", value: "ch" },
  { label: "Thailand", value: "th" },
  { label: "Turkey", value: "tr" },
  { label: "Ukraine", value: "ua" },
  { label: "United Kingdom", value: "gb" },
  { label: "United States", value: "us" },
  { label: "Vietnam", value: "vn" },
];

export const Categories: string[] = [
  "Business",
  "Entertainment",
  "Environment",
  "Food",
  "Health",
  "Politics",
  "Sports",
  "Science",
  "Technology",
  "Top",
  "Tourism",
  "World",
];
